### ISSUE TITLE
Crash when using Cotton Resources 1.15

### ISSUE THREAD

**Issue by ixanza** [CottonMC/Vivatech#11] opened 2019-05-30 06:22 UTC
Mod List : 
```
cotton-0.6.9+1.14.2-SNAPSHOT
cotton-energy-1.3.2+1.14.2-SNAPSHOT
cotton-resources-1.1.5+1.14.1-SNAPSHOT
fabric-api-0.3.0+build.175
libblockattributes-0.4.2
RoughlyEnoughItems-2.9.1+build.116
vivatech-1.0.0-alpha.1
```

The game launches fine using 1.14 but there is no recipe for the Machine Chassis or the Electric Furnace

Crash Log

> MultiMC version: 0.6.5-develop-1308
> 
> 
> Minecraft folder is:
> C:/Games/MultiMC/instances/multimc/.minecraft
> 
> 
> Java path is:
> C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe
> 
> 
> Java is version 1.8.0_201, using 64-bit architecture.
> 
> 
> Main Class:
>   net.fabricmc.loader.launch.knot.KnotClient
> 
> Native path:
>   C:/Games/MultiMC/instances/multimc/natives
> 
> Traits:
> traits FirstThreadOnMacOS
> 
> Libraries:
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
>   C:/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
>   C:/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
>   C:/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
>   C:/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
>   C:/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
>   C:/Games/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
>   C:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
>   C:/Games/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
>   C:/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
>   C:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
>   C:/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
>   C:/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
>   C:/Games/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
>   C:/Games/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
>   C:/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
>   C:/Games/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
>   C:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
>   C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
>   C:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
>   C:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
>   C:/Games/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
>   C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
>   C:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
>   C:/Games/MultiMC/libraries/com/mojang/realms/1.14.16/realms-1.14.16.jar
>   C:/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/fabric-loader/0.4.8+build.154/fabric-loader-0.4.8+build.154.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/yarn/1.14.2+build.2/yarn-1.14.2+build.2.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.36/sponge-mixin-0.7.11.36.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar
>   C:/Games/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
>   C:/Games/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
>   C:/Games/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
>   C:/Games/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
>   C:/Games/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
>   C:/Games/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
>   C:/Games/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
>   C:/Games/MultiMC/libraries/com/mojang/minecraft/1.14.2/minecraft-1.14.2-client.jar
> 
> Native libraries:
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-windows.jar
>   C:/Games/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
> 
> Mods:
>   cotton-0.6.9+1.14.2-SNAPSHOT
>   cotton-energy-1.3.2+1.14.2-SNAPSHOT
>   cotton-resources-1.1.5+1.14.1-SNAPSHOT
>   fabric-api-0.3.0+build.175
>   libblockattributes-0.4.2
>   RoughlyEnoughItems-2.9.1+build.116
>   vivatech-1.0.0-alpha.1
> 
> Params:
>   --username  --version MultiMC5 --gameDir C:/Games/MultiMC/instances/multimc/.minecraft --assetsDir C:/Games/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release
> 
> Window size: 1660 x 900
> 
> Java Arguments:
> [-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx6144m, -Duser.language=en]
> 
> 
> Minecraft process ID: 17768
> 
> 
> Using onesix launcher.
> 
> [14:21:13] [main/INFO]: Loading for game Minecraft 1.14.2
> [14:21:15] [main/INFO]: [FabricLoader] Loading 34 mods: fabric-renderer-api-v1@0.1.0+02a46d5b, fabric-networking-blockentity-v0@0.1.1+25fd0c52, fabric-keybindings-v0@0.1.0+59147463, fabricloader@0.4.8+build.154, cotton-resources@1.1.5+1.14.1, cotton@0.6.9+1.14.2-SNAPSHOT, fabric-renderer-indigo@0.1.4+620b4d61, fabric-containers-v0@0.1.2+25fd0c52, roughlyenoughitems@2.9.1+build.116, fabric-crash-report-info-v1@0.1.0+59147463, fabric-events-interaction-v0@0.1.0+59147463, vivatech@1.0.0-alpha.1, fabric-api-base@0.1.0+59147463, libblockattributes@0.4.2, fabric-rendering-v0@0.1.0+59147463, cotton-energy@1.3.2+1.14.2, fabric-rendering-data-attachment-v1@0.1.0+02a46d5b, fabric-resource-loader-v0@0.1.1+59147463, fabric-textures-v0@0.1.4+792c1c35, fabric-content-registries-v0@0.1.1+45e1a1c8, fabric-tag-extensions-v0@0.1.0+59147463, blue_endless_jankson@1.1.0, fabric-rendering-fluids-v1@0.1.0+dc4c57c2, fabric-registry-sync-v0@0.2.1+4d26f9ba, fabric-commands-v0@0.1.1+25fd0c52, cloth-config@0.2.1+build.14, fabric-mining-levels-v0@0.1.0+59147463, fabric-events-lifecycle-v0@0.1.0+9232ac87, fabric@0.3.0+build.175, fabric-item-groups-v0@0.1.0+59147463, fabric-models-v0@0.1.0+59147463, fabric-networking-v0@0.1.2+200eb5c2, fabric-object-builders-v0@0.1.1+9fe2f882, cloth@0.3.1+build.23
> [14:21:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Games/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.36/sponge-mixin-0.7.11.36.jar Service=Knot/Fabric Env=CLIENT
> [14:21:16] [main/INFO]: Compatibility level set to JAVA_8
> [14:21:16] [main/WARN]: Mixin config fabric-networking-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-mining-levels-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-renderer-indigo.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-rendering-data-attachment-v1.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-textures-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-models-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-keybindings-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-renderer-api-v1.debughud.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-containers-v0.accurate.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-events-lifecycle-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-rendering-fluids-v1.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config cotton.common.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config cotton-resources.common.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-rendering-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-commands-v0.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Mixin config fabric-renderer-api-v1.mixins.json does not specify "minVersion" property
> [14:21:16] [main/WARN]: Error loading class: net/minecraft/world/biome/DefaultBiomeFeatures (java.lang.ClassNotFoundException: net/minecraft/world/biome/DefaultBiomeFeatures)
> [14:21:16] [main/WARN]: @Mixin target net.minecraft.world.biome.DefaultBiomeFeatures was not found cotton-resources.common.json:MixinVanillaOregen
> [14:21:17] [main/INFO]: Setting user: iXanza
> ---- Minecraft Crash Report ----
> // Sorry :(
> 
> Time: 5/30/19 2:21 PM
> Description: Initializing game
> 
> java.lang.NoClassDefFoundError: net/minecraft/util/registry/Registry
> 	at io.github.cottonmc.resources.config.OreGenerationSettings.getDefault(OreGenerationSettings.java:59)
> 	at io.github.cottonmc.resources.config.CottonResourcesConfig.<init>(CottonResourcesConfig.java:18)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at java.lang.Class.newInstance(Unknown Source)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:81)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:52)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:48)
> 	at io.github.cottonmc.resources.CottonResources.<clinit>(CottonResources.java:14)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
> 	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
> 	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
> 	at net.minecraft.class_310.method_1503(class_310.java)
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at io.github.cottonmc.resources.config.OreGenerationSettings.getDefault(OreGenerationSettings.java:59)
> 	at io.github.cottonmc.resources.config.CottonResourcesConfig.<init>(CottonResourcesConfig.java:18)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at java.lang.Class.newInstance(Unknown Source)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:81)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:52)
> 	at io.github.cottonmc.cotton.config.ConfigManager.loadConfig(ConfigManager.java:48)
> 	at io.github.cottonmc.resources.CottonResources.<clinit>(CottonResources.java:14)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:101)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:93)
> 	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:140)
> 	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
> 	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
> 	at net.minecraft.class_310.method_1503(class_310.java)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.14.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_201, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1800008072 bytes (1716 MB) / 2321547264 bytes (2214 MB) up to 5726797824 bytes (5461 MB)
> 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx6144m
> 	Fabric Mods: 
> 		blue_endless_jankson: jankson 1.1.0
> 		cloth: Cloth Events 0.3.1+build.23
> 		cloth-config: Cloth Config 0.2.1+build.14
> 		cotton: Cotton 0.6.9+1.14.2-SNAPSHOT
> 		cotton-energy: Cotton Energy 1.3.2+1.14.2
> 		cotton-resources: Cotton Resources 1.1.5+1.14.1
> 		fabric: Fabric API 0.3.0+build.175
> 		fabric-api-base: fabric-api-base 0.1.0+59147463
> 		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
> 		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
> 		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
> 		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
> 		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
> 		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+9232ac87
> 		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
> 		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+59147463
> 		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
> 		fabric-models-v0: fabric-models-v0 0.1.0+59147463
> 		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
> 		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
> 		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
> 		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.1+4d26f9ba
> 		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
> 		fabric-renderer-indigo: fabric-renderer-indigo 0.1.4+620b4d61
> 		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
> 		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
> 		fabric-rendering-v0: fabric-rendering-v0 0.1.0+59147463
> 		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
> 		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+59147463
> 		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
> 		fabricloader: Fabric Loader 0.4.8+build.154
> 		libblockattributes: LibBlockAttributes 0.4.2
> 		roughlyenoughitems: Roughly Enough Items 2.9.1+build.116
> 		vivatech: Vivatech 1.0.0-alpha.1
> 	Launched Version: MultiMC5
> 	LWJGL: 3.2.1 build 12
> 	OpenGL: NO CONTEXT
> 	GL Caps: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Resource Packs: ~~ERROR~~ NullPointerException: null
> 	Current Language: ~~ERROR~~ NullPointerException: null
> 	CPU: <unknown>
> #@!@# Game crashed! Crash report saved to: #@!@# C:\Games\MultiMC\instances\multimc\.minecraft\crash-reports\crash-2019-05-30_14.21.19-client.txt
> Process exited with code -1.

**Comment by Juuxel** [comment] 2019-05-30 06:31
> `java.lang.NoClassDefFoundError: net/minecraft/util/registry/Registry`

Looks like the Cotton Resources build might be broken and not properly remapped.

**Comment by falseresync** [comment] 2019-05-30 08:00
Yes, it is a Cotton Resources problem. I won’t close this yet, until it’s fixed. We’re working on it right now

**Comment by falseresync** [comment] 2019-05-30 08:03
Right now try to use Fabric API build 173.
There won’t be a recipe for these blocks until the problem is resolved on the Cotton Resources end.

**Comment by falseresync** [comment] 2019-05-30 11:04
New version of Cotton Resources is already uploaded to Maven and soon will be to CurseForge. New version of Vivatech will be soon published on CurseForge

**Closed as completed by falseresync** 2019-05-30 11:04 UTC
